# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resume',
            field=models.CharField(default='aucune description', max_length=100),
            preserve_default=False,
        ),
    ]
