# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/None/affiche-warriors-movie.jpg', upload_to='images/'),
        ),
    ]
