# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180221_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_lien',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/static/image/affiche-warriors-movie.jpg', upload_to='blog/static/image'),
        ),
    ]
