# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180222_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='image/affiche-warriors-movie.jpeg', upload_to='image'),
        ),
    ]
