# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-09 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180307_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Publique',
            field=models.BooleanField(default=True),
        ),
    ]
